### ISSUE TITLE
Froala CDN

### ISSUE THREAD

**Issue by Ilyes-Hammadi** [froala/design-blocks#27] opened 2017-10-17 21:00 UTC
I have started using this project today and I absolutely love it. I would like to suggest to support for Froala on CDN, it will be nice if we can just add the CDN to a project and copy and paste the code and see everything working well.

**Comment by stefanneculai** [comment] 2017-10-17 21:12
Duplicate of #8. Will be added shortly.

**Comment by Ilyes-Hammadi** [comment] 2017-10-17 21:16
Thank you, can't wait for that

**Closed** 2017-10-17 21:29 UTC
